language: ruby
rvm:
  - '2.2.1'
  - '2.1.5'
  # ALLOWED FAILURES #
  # How compatible are we with dev versions? Research/guidance only; failures don't matter. Yet.
  - ruby-head
  - jruby-9.0.0.0.pre1
  - jruby-head
allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  - rvm: jruby-9.0.0.0.pre1
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.travis config/database.yml
  # Carry-over from CodeShip; if we commit to Travis, this can be simplified.
  - bundle exec rake db:schema:load
  - bundle exec rake db:reset
  - bundle exec rake db:seed
